export const NAVIGATOR_SCREEN = {
  CLASS_TEACHER: "CLASS_TEACHER",
  CLASS_STUDENT: "CLASS_STUDENT",
  LOGIN: "LOGIN",
  TEACHER: "TEACHER",
  STUDENT: "STUDENT",
  STUDENT_IN_CLASS: "STUDENT_IN_CLASS",
  HISTORY_TEACHER: "HISTORY_TEACHER",
  HISTORY_TEACHER_DATE: "HISTORY_TEACHER_DATE",
  PROFILE: "PROFILE",
  NOTIFY_STUDENT: "NOTIFY_STUDENT",
};

export const SERVER_URL = "http://192.168.200.215:9002/";
